
ui <- navbarPage("Name That Tune!",
                 id = "general_tab",
                 ###############################################################
                 tabPanel("Devices",
                          shinyjs::useShinyjs(),
                          includeCSS("./www/style.css"),
                          h1("Let's play Name That Tune!"),
                          br(),
                          br(),
                          h3("Select the device:"),
                          selectInput("devices",
                                      label = " ",
                                      choices = " ",
                                      selected = NULL),
                          actionButton("refresh", "Refresh")
                 ),
                 ###############################################################
                 tabPanel("Players",
                          h3("Choose players and set their names:"),
                          br(),
                          br(),
                          column(3,
                                 numericInput("n_players",
                                              label = "Number of players",
                                              value = 1,
                                              min = 1,
                                              max = 10),
                                 uiOutput("text_windows")
                          ),
                          verbatimTextOutput("choice")
                 ),

                 ###############################################################
                 tabPanel("Playlist",
                          column(5,
                                 h3("Choose playlist and press START if you are ready!"),
                                 div(style = "display:center-align",
                                     actionButton("start", "S T A R T", width = 150)),

                                 br(),
                                 selectInput("playlists",
                                             label = "Playlist:",
                                             choices = c(),
                                             selected = c()),
                                 "Note: The first 30 playlists loaded.",
                                 br(),
                                 br(),
                                 h4("Your choice:")
                          ),
                          column(7,
                                 htmlOutput("playlist_image")
                          ),
                          br(),
                          br(),
                          column(12,
                                 shinycssloaders::withSpinner(tableOutput("playlist_content"),
                                                              color = "#1c6e8c")
                          )
                 ),
                 ###############################################################
                 tabPanel("Game",
                          h3("Currently playing:"),
                          br(),
                          column(2, htmlOutput("album")),
                          column(10, verbatimTextOutput("current_song")),
                          br(),
                          br(),
                          br(),
                          br(),
                          br(),
                          br(),
                          br(),
                          br(),
                          br(),
                          br(),
                          br(),
                          h3("Scores:"),
                          column(3, tableOutput("print_scores")),
                          column(3,
                                 checkboxGroupInput("author_point",
                                                    "Point for the author goes to:",
                                                    choices = c(""))
                          ),
                          column(3,
                                 checkboxGroupInput("title_point",
                                                    "Point for the title goes to:",
                                                    choices = c(""))
                          ),
                          column(3,
                                 checkboxGroupInput("extra_point",
                                                    "Point for a fun fact goes to:",
                                                    choices = c(""))
                          ),
                          br(),
                          br(),
                          br(),
                          br(),
                          br(),
                          br(),
                          br(),
                          br(),
                          br(),
                          br(),
                          br(),
                          br(),
                          column(4, actionButton("prev_button", "Previous song")),
                          column(2, actionButton("pause_button", "Pause")),
                          column(2, actionButton("play_button", "Play")),
                          column(2),
                          column(2, actionButton("next_button", "Next song"))
                 ),
                 ###############################################################
                 tabPanel("Summary",
                          h3("Results:"),
                          column(12,
                                 tableOutput("overall_results"),
                                 downloadButton("download_scores")),
                          br(),
                          br(),
                          br(),
                          column(3,
                                 br(),
                                 br(),
                                 br(),
                                 checkboxGroupInput("category",
                                                    "Category:",
                                                    choices = c("author",
                                                                "title",
                                                                "fun fact"),
                                                    selected = c("author",
                                                                 "title",
                                                                 "fun fact")),
                                 checkboxGroupInput("players_plot",
                                                    "Players:",
                                                    choices = c(""))),
                          column(9, plotOutput("results_vis"))
                 )
)
